const types = {
  // GET
  GET_USERS_START: "GET_USERS_START",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_ERROR: "GET_USERS_ERROR",

  // POST
  POST_USER_START: "POST_USER_START",
  POST_USER_SUCCESS: "POST_USER_SUCCESS",
  POST_USER_ERROR: "POST_USER_ERROR",

  // DELETE
  DELETE_USER_START: "DELETE_USER_START",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_ERROR: "DELETE_USER_ERROR",

  // PUT
  PUT_USER_START: "PUT_USER_START",
  PUT_USER_SUCCESS: "PUT_USER_SUCCESS",
  PUT_USER_ERROR: "PUT_USER_ERROR",
};

export default types;
